### ISSUE TITLE
addiction problems Thank you for your work so far, I hope they can find a solution.

### ISSUE THREAD

**Issue by badam1991** [Joansitoh/edge-profile-manager#1]
I was very happy with the project

There are too many dependencies and it always crashes, can you write a description of what is needed or a package that contains all the necessary elements

From the point of view of user comfort in an office, if we were to use edge instead of chrome, it would be a great convenience tool.

C:\Users\USER\Downloads\edge_profile_manager-master>pip install PyQt5
Requirement already satisfied: PyQt5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (5.15.10)
Requirement already satisfied: PyQt5-sip<13,>=12.13 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from PyQt5) (12.13.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from PyQt5) (5.15.2)

C:\Users\USER\Downloads\edge_profile_manager-master>
C:\Users\USER\Downloads\edge_profile_manager-master>pip install -r requirements.txt
Collecting async-generator==1.10 (from -r requirements.txt (line 1))
  Using cached async_generator-1.10-py3-none-any.whl.metadata (4.9 kB)
Collecting attrs==22.2.0 (from -r requirements.txt (line 2))
  Using cached attrs-22.2.0-py3-none-any.whl.metadata (13 kB)
Collecting certifi==2022.12.7 (from -r requirements.txt (line 3))
  Using cached certifi-2022.12.7-py3-none-any.whl.metadata (2.9 kB)
Collecting cffi==1.15.1 (from -r requirements.txt (line 4))
  Using cached cffi-1.15.1.tar.gz (508 kB)
  Preparing metadata (setup.py) ... done
Collecting exceptiongroup==1.1.1 (from -r requirements.txt (line 5))
  Using cached exceptiongroup-1.1.1-py3-none-any.whl.metadata (6.1 kB)
Collecting h11==0.14.0 (from -r requirements.txt (line 6))
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting idna==3.4 (from -r requirements.txt (line 7))
  Using cached idna-3.4-py3-none-any.whl.metadata (9.8 kB)
Collecting install==1.3.5 (from -r requirements.txt (line 8))
  Using cached install-1.3.5-py3-none-any.whl.metadata (925 bytes)
Collecting outcome==1.2.0 (from -r requirements.txt (line 9))
  Using cached outcome-1.2.0-py2.py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pycparser==2.21 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 10)) (2.21)
Collecting PyQt5==5.15.9 (from -r requirements.txt (line 11))
  Using cached PyQt5-5.15.9-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
Requirement already satisfied: PyQt5-Qt5==5.15.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 12)) (5.15.2)
Collecting PyQt5-sip==12.11.1 (from -r requirements.txt (line 13))
  Using cached PyQt5_sip-12.11.1.tar.gz (122 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PySocks==1.7.1 (from -r requirements.txt (line 14))
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting selenium==4.8.2 (from -r requirements.txt (line 15))
  Using cached selenium-4.8.2-py3-none-any.whl.metadata (7.2 kB)
Collecting sniffio==1.3.0 (from -r requirements.txt (line 16))
  Using cached sniffio-1.3.0-py3-none-any.whl.metadata (3.6 kB)
Collecting sortedcontainers==2.4.0 (from -r requirements.txt (line 17))
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting trio==0.22.0 (from -r requirements.txt (line 18))
  Using cached trio-0.22.0-py3-none-any.whl.metadata (4.6 kB)
Collecting trio-websocket==0.10.2 (from -r requirements.txt (line 19))
  Using cached trio_websocket-0.10.2-py3-none-any.whl.metadata (4.6 kB)
Collecting urllib3==1.26.15 (from -r requirements.txt (line 20))
  Using cached urllib3-1.26.15-py2.py3-none-any.whl.metadata (48 kB)
Collecting wsproto==1.2.0 (from -r requirements.txt (line 21))
  Using cached wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Using cached exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Using cached idna-3.4-py3-none-any.whl (61 kB)
Using cached install-1.3.5-py3-none-any.whl (3.2 kB)
Using cached outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Using cached PyQt5-5.15.9-cp37-abi3-win_amd64.whl (6.8 MB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached selenium-4.8.2-py3-none-any.whl (6.9 MB)
Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Using cached trio-0.22.0-py3-none-any.whl (384 kB)
Using cached trio_websocket-0.10.2-py3-none-any.whl (17 kB)
Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Building wheels for collected packages: cffi, PyQt5-sip
  Building wheel for cffi (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      _configtest.c
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\cffi
      copying cffi\api.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\backend_ctypes.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\cffi_opcode.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\commontypes.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\cparser.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\error.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\ffiplatform.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\lock.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\model.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\pkgconfig.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\recompiler.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\setuptools_ext.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\vengine_cpy.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\vengine_gen.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\verifier.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\__init__.py -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\_cffi_include.h -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\parse_c_type.h -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\_embedding.h -> build\lib.win-amd64-cpython-312\cffi
      copying cffi\_cffi_errors.h -> build\lib.win-amd64-cpython-312\cffi
      running build_ext
      building '_cffi_backend' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\c
      creating build\temp.win-amd64-cpython-312\Release\c\libffi_x86_x64
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DFFI_BUILDING=1 -Ic/libffi_x86_x64 -IC:\Users\USER\AppData\Local\Programs\Python\Python312\include -IC:\Users\USER\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcc/_cffi_backend.c /Fobuild\temp.win-amd64-cpython-312\Release\c/_cffi_backend.obj
      _cffi_backend.c
      C:\Users\USER\AppData\Local\Programs\Python\Python312\include\pyconfig.h(230): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cffi
  Running setup.py clean for cffi
  Building wheel for PyQt5-sip (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for PyQt5-sip (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'PyQt5.sip' extension
      creating build
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\USER\AppData\Local\Programs\Python\Python312\include -IC:\Users\USER\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcapiversions.c /Fobuild\temp.win-amd64-cpython-312\Release\apiversions.obj
      apiversions.c
      C:\Users\USER\AppData\Local\Programs\Python\Python312\include\pyconfig.h(230): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyQt5-sip
Failed to build cffi PyQt5-sip
ERROR: Could not build wheels for cffi, PyQt5-sip, which is required to install pyproject.toml-based projects

C:\Users\USER\Downloads\edge_profile_manager-master>

**Comment by Joansitoh** [comment]
Thank you for your words, I will resume the project for fix and implement a simpler installation solution!
